version: '3'

volumes:
  dados:

services:    
  petz-db:
    image: postgres:13.1
    volumes:
      - dados:/var/lib/postgresql/data
#      - ./src/main/resources/postgres/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=petz
      - POSTGRES_DB=petzdb
    networks:
      - petz-compose-network
    
  pgadmin-service:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=petz@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=petz
    ports: 
      - 15432:80
    networks:
      - petz-compose-network
  
  petz-api:
    build: .
    image: petz-api:latest
    environment:
     - DATABASE_URL=postgres://postgres:petz@petz-db:5432/petzdb
    ports:
      - 8090:8080
    networks: 
      - petz-compose-network
    depends_on:
      - petz-db
    
networks:
  petz-compose-network:
    name: petz-compose-network
    driver: bridge
